name: CI
on:
  push:
    branches:
      - main
      - develop
      - release/*
  pull_request:
    branches:
      - main
      - release/*
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.11"
          - "3.14"
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
        with:
          version: 0.7.5
          python-version: ${{ matrix.python-version }}
          enable-cache: false
          cache-dependency-glob: uv.lock
      - name: Install system dependencies
        run: |
          sudo apt update && sudo apt install -y build-essential libpython3-dev libglib2.0-dev
      - name: Install
        run: |
          uv sync --all-extras --dev
      - name: Lint
        run: |
          uv run --frozen ruff check src/
      - name: Test
        run: |
          uv run --frozen coverage run -m pytest
      - name: Generate coverage XML
        run: |
          uv run --frozen coverage xml
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

